config/routes.rb
Bicicletea::Application.routes.draw do

  
  
  get 'paginas_estaticas/contacto'

  get 'paginas_estaticas/sobreNosotros'

  root 'welcome#index'
  resources :products, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :projects, only: [:index, :show]

  resources :posts, only: [:index, :show]
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  devise_for :editors, controllers: { sessions: "editors/sessions", passwords: "editors/passwords" }
  devise_for :super_admins, :module => 'super_admin', path: "super_admin", controllers: { sessions: "super_admin/sessions", passwords: "super_admin/passwords" }

  namespace :editors do
    resources :dashboard, only: [:index]
  end

  namespace :super_admin do
    resources :dashboard, only: [:index]
    resources :posts
    resources :categories
    resources :subcategories
    resources :products
    resources :project_types
    resources :projects
    resources :webimages
  end

end

app/models/super_admin.rb
class SuperAdmin < Admin
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable,
    :rememberable, :trackable, :validatable
end

app/models/super_admin/comentario.rb
class SuperAdmin::Comentario < ActiveRecord::Base
end

app/models/webimage.rb
class Webimage < ActiveRecord::Base
  validates :title,  presence: true

  has_many :images

  accepts_nested_attributes_for :images, :reject_if => :all_blank, :allow_destroy => true

  has_attached_file :image, :styles => { :normal => "1600x680>", :thumb => "1600x680#" }, :default_url => "http://placehold.it/500x500"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/controllers/super_admin/categories_controller.rb
class SuperAdmin::CategoriesController < SuperAdminController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to ([:super_admin, @category]), notice: 'Categoria creada correctamente.' }
        format.json { render action: 'show', status: :created, category: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @category = Category.friendly.find(params[:id])
    respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @category }
    end
  end

  def update

        respond_to do |format|
    	      if @category.update_attributes(category_params)
    	        format.html { redirect_to ([:super_admin, @category]), notice: 'Categoria actualizada correctamente.' }
    	        format.json { head :no_content }
    	      else
    	        format.html { render action: "edit" }
    	        format.json { render json: @category.errors, status: :unprocessable_entity }
    	      end
    	    end
  end

  def destroy

    @category.destroy
    respond_to do |format|

      format.html { redirect_to ([:super_admin, @category]), :notice => "Categoria eliminada correctamente." }
      format.js {list_refresh}
    end
  end

  private

      # Never trust parameters from the scary internet, only allow the white list through.
      def category_params
        params.require(:category).permit(
          :parent_id,
          :title,
          :description,
          :meta_description,
          :featured,
          :image,
          :images_attributes => [:id, :photo, :headline, :caption, :done, :_destroy]
        )
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_category
        @category = Category.find(params[:id])
      end
end

app/controllers/super_admin/confirmations_controller.rb
class SuperAdmin::ConfirmationsController < Devise::ConfirmationsController
  layout "super_admin"
end # Save contents to file using 'Control + D'

app/controllers/super_admin/dashboard_controller.rb
class SuperAdmin::DashboardController < SuperAdminController
  def index
  end
end # After typing end press 'Control + D' to save file

app/controllers/super_admin/passwords_controller.rb
class SuperAdmin::PasswordsController < Devise::PasswordsController
  layout "super_admin"
end # Save contents to file using 'Control + D'

app/controllers/super_admin/posts_controller.rb
class SuperAdmin::PostsController < SuperAdminController
  before_action :set_post, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def new
    @post = Post.new
  end

  def edit

  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to ([:super_admin, @post]), notice: 'Post fue correctamente creado.' }
        format.json { render action: 'show', status: :created, post: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @post = Post.friendly.find(params[:id])
    respond_to do |format|
	      format.html # show.html.erb
	      format.json { render json: @post }
	  end
  end

  def update

    respond_to do |format|
	      if @post.update_attributes(post_params)
	        format.html { redirect_to ([:super_admin, @post]), notice: 'Post actualizado correctamente.' }
	        format.json { head :no_content }
	      else
	        format.html { render action: "edit" }
	        format.json { render json: @post.errors, status: :unprocessable_entity }
	      end
	    end
  end

  def destroy
    @post.destroy
    respond_to do |format|

      format.html { redirect_to ([:super_admin, @post]), :notice => "Post eliminado correctamente." }
      format.js {list_refresh}
    end
  end

  private

      # def list_refresh
      #   if params[:show_posts] == 'true'
      #     @posts = Post.where(:page_id => params[:id]).paginate(:page => params[:page], :per_page => 20).order('position ASC')
      #     return render(:file => 'admin/posts/show_list_refresh.js.erb')
      #   else
      #     @pages = Page.paginate(:page => params[:page], :per_page => 10).order('name ASC')
      #     return render(:file => 'admin/posts/list_refresh.js.erb')
      #   end
      # end

      # Never trust parameters from the scary internet, only allow the white list through.
      def post_params
        params.require(:post).permit(
          :title,
          :body,
          :published,
          :meta_description,
          :image,
          :images_attributes => [:id, :photo, :headline, :caption, :done, :_destroy]
        )
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.find(params[:id])
      end

end

app/controllers/super_admin/products_controller.rb
class SuperAdmin::ProductsController < SuperAdminController
  before_action :set_product, only: [:edit, :update, :destroy]

  def index
    # looks like that join is just a sql query! easy! Too bad the relationships don't get diagrammed in activerecord. **There is a gem that generates a read-only erd.
    # @products = Product.joins('LEFT JOIN subcategories ON products.subcategory_id = subcategories.id')
    # HERE is the rails way to do the join. Could it be any easier?
    @products = Product.joins(:category)
    #@products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  def new
    @product = Product.new
    #@subcategory = Subcategory.find(params[:product_id])
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to ([:super_admin, @product]), notice: 'Producto creado correctamente.' }
        format.json { render action: 'show', status: :created, product: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @product = Product.friendly.find(params[:id])
    respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @product }
    end
  end

  def update

    respond_to do |format|
        if @product.update_attributes(product_params)
          format.html { redirect_to ([:super_admin, @product]), notice: 'Producto actualizado correctamente.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
  end

  def destroy
    @product.destroy
    respond_to do |format|

      format.html { redirect_to ([:super_admin, @product]), :notice => "Productos eliminado correctamente." }
      format.js {list_refresh}
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(
      :title,
      :description,
      :meta_description,
      :featured,
      :image,
      :category_id,
      :precio,
      :images_attributes => [:id, :photo, :headline, :caption, :done, :_destroy]
    )
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end
end

app/controllers/super_admin/project_types_controller.rb
class SuperAdmin::ProjectTypesController < SuperAdminController
  before_action :set_project_type, only: [:edit, :update, :destroy]
  def index
    @project_types = ProjectType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @project_types }
    end
  end

  def new
    @project_type = ProjectType.new
  end

  def edit
  end

  def create
    @project_type = ProjectType.new(project_type_params)
    #@category = Category.find(params[:product][:category_id])
    respond_to do |format|
      if @project_type.save
        format.html { redirect_to ([:super_admin, @project_type]), notice: 'Tipo de Proyecto creado correctamente.' }
        format.json { render action: 'show', status: :created, product: @project_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @project_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @project_type = ProjectType.friendly.find(params[:id])
    respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @Project_type }
    end
  end

  def update

    respond_to do |format|
        if @project_type.update_attributes(project_type_params)
          format.html { redirect_to ([:super_admin, @project_type]), notice: 'Tipo de Proyecto actualizado correctamente.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @project_type.errors, status: :unprocessable_entity }
        end
      end
  end

  def destroy
    @project_type.destroy
    respond_to do |format|

      format.html { redirect_to ([:super_admin, @project_type]), :notice => "Tipo de Proyecto eliminado correctamente." }
      format.js {list_refresh}
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def project_type_params
    params.require(:project_type).permit(
      :title,
      :description,

    )
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_project_type
    @project_type = ProjectType.find(params[:id])
  end
end

app/controllers/super_admin/projects_controller.rb
class SuperAdmin::ProjectsController < SuperAdminController
  before_action :set_project, only: [:edit, :update, :destroy]
  def index
    @projects = Project.joins(:product)
    #@products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    #@category = Category.find(params[:product][:category_id])
    respond_to do |format|
      if @project.save
        format.html { redirect_to ([:super_admin, @project]), notice: 'Proyecto creado correctamente.' }
        format.json { render action: 'show', status: :created, product: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @project = Project.friendly.find(params[:id])
    respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @project }
    end
  end

  def update

    respond_to do |format|
        if @project.update_attributes(project_params)
          format.html { redirect_to ([:super_admin, @project]), notice: 'Producto actualizado correctamente.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
  end

  def destroy
    @project.destroy
    respond_to do |format|

      format.html { redirect_to ([:super_admin, @project]), :notice => "Productos eliminado correctamente." }
      format.js {list_refresh}
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(
      :title,
      :description,
      :meta_description,
      :featured,
      :image,
      :place,
      :category_id,
      :product_id,
      :project_type_id,
      :images_attributes => [:id, :photo, :headline, :caption, :done, :_destroy]
    )
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end
end

app/controllers/super_admin/sessions_controller.rb
class SuperAdmin::SessionsController < Devise::SessionsController
  layout "super_admin"

  private
    def after_sign_in_path_for(resource)
      session[:super_admin_return_to].blank? ? super_admin_dashboard_index_path : session[:super_admin_return_to]
    end

    def after_sign_out_path_for(resource_or_scope)
      new_super_admin_session_path
    end
end # Save using 'Control + D'

app/controllers/super_admin/webimages_controller.rb
class SuperAdmin::WebimagesController < SuperAdminController
  before_action :set_webimage, only: [:show, :edit, :update, :destroy]

  def index
    @webimages = Webimage.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @webimages }
    end
  end

  def new
    @webimage = Webimage.new
  end

  def edit
  end

  def create
    @webimage = Webimage.new(webimage_params)
    #@category = Category.find(params[:product][:category_id])
    respond_to do |format|
      if @webimage.save
        format.html { redirect_to ([:super_admin, @webimage]), notice: 'Imagen creada correctamente.' }
        format.json { render action: 'show', status: :created, product: @webimage }
      else
        format.html { render action: 'new' }
        format.json { render json: @webimage.errors, status: :unprocessable_entity }
      end
    end
  end

  def show

  end

  def update

    respond_to do |format|
        if @webimage.update_attributes(webimage_params)
          format.html { redirect_to ([:super_admin, @webimage]), notice: 'Imagen actualizada correctamente.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @webimage.errors, status: :unprocessable_entity }
        end
      end
  end

  def destroy
    @webimage.destroy
    respond_to do |format|

      format.html { redirect_to ([:super_admin, @webimage]), :notice => "Imagen eliminada correctamente." }
      format.js {list_refresh}
    end
  end


  def options_for_modules
    [
      ['First Option','first_option'],
      ['Second Option','second_option']
    ]
  end
  
  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def webimage_params
    params.require(:webimage).permit(
      :title,
      :module,
      :image,
      :images_attributes => [:id, :photo, :headline, :caption, :done, :_destroy]
    )
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_webimage
    @webimage = Webimage.find(params[:id])
  end


end

app/controllers/super_admin_controller.rb
class SuperAdminController < ApplicationController
  layout 'super_admin'
  before_action :authenticate_super_admin!
end  # After typing end press 'Control + D' to save file

app/helpers/super_admin/categories_helper.rb
module SuperAdmin::CategoriesHelper
end

app/helpers/super_admin/posts_helper.rb
module SuperAdmin::PostsHelper
end

app/helpers/super_admin/products_helper.rb
module SuperAdmin::ProductsHelper
end

app/helpers/super_admin/project_types_helper.rb
module SuperAdmin::ProjectTypesHelper
end

app/helpers/super_admin/projects_helper.rb
module SuperAdmin::ProjectsHelper
end

app/helpers/super_admin/webimages_helper.rb
module SuperAdmin::WebimagesHelper
end

app/views/super_admin/webimages/_form.html.erb
<%= form.input :module, :collection => [['CABECERA PAGINA PRINCIPAL', :FRONTSLIDER], ['PIE PAGINA PRINCIPAL', :FRONTFOOTER]] %>

<div class="row">
	<div class="col-sm-12">

		<%= form.input :title %>
		<hr />
	</div>
</div>

<div class="row">
	<div class="col-sm-6">
		<h3>Imagen principal</h3>
		<% unless @webimage.image.blank? %>
			<div class="image_preview">
				<%= image_tag(@webimage.image.url(:thumb)) %>
			</div>
		<% end %>
		<%= form.input :image %>
	</div>
</div>

<hr />

<h3>Images</h3>
<div class="row images">
	<%= form.simple_fields_for :images do |image| %>
		<%= render 'image_fields', :f => image %>
	<% end %>


	<div class="links">
		<%= link_to_add_association form, :images do %>
			<span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> add image
		<% end %>
	</div>
</div>
<hr />


<div class="form-actions">
  <% label = @webimage.new_record? ? "Crear" : "Actualizar" -%>
  <%= form.submit label, :class => 'btn btn-primary' %>
  &nbsp;
  <%= link_to "cancelar", super_admin_webimages_path, :class => 'btn btn-default' %>
</div>

app/views/super_admin/webimages/_image_fields.html.erb
<div class="nested-fields col-sm-6">
	<% unless f.object.photo.blank? %>
		<div class="image_preview">
			<%= image_tag(f.object.photo.url(:thumb)) %>
		</div>
	<% end %>

  <%= f.input :photo, required: false %>
  <div class="text-right">
	  <%= link_to_remove_association f do %>
	  	<span class="glyphicon glyphicon-minus-sign" aria-hidden="true"></span> Remove Image
	 	<% end %>
	</div>
</div>

app/views/super_admin/webimages/_list.html.erb
<% for @webimage in @webimages %>
	<div class="module_item">
		<div class="item_name">
			<span><%= link_to @webimage.title, :controller => 'super_admin/webimages', :action => 'edit', :id => @webimage.id%></span>
		</div>
		<div class="module_item_actions">
			<p>
				<%= link_to '<span class="glyphicon glyphicon-file"></span>'.html_safe, super_admin_webimage_path(@webimage.id), :class => 'list-row-action-wrapper-link' %>
 			  <%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_super_admin_webimage_path(@webimage.id), :class => 'list-row-action-wrapper-link' %>
				<%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, super_admin_webimage_path(@webimage.id), :class => 'list-row-action-delete-one list-row-action-wrapper-link', :method => :delete, :data => {:confirm => "Estas seguro?"} %>
			</p>
		</div>
		<div class="clearboth"></div>
	</div>
<% end %>

app/views/super_admin/webimages/edit.html.erb
<div class="page-header clearfix">
<div class="title">
	<h1>Editando Imagenes</h1>
</div>
<hr />
<%= render :partial => 'super_admin/template/form_errors', :object => @webimage %>

<%= simple_form_for @webimage, :url => url_for(:controller => 'super_admin/webimages', :action => 'update'), :method => 'put', :html => { :role => "form" } do |form| %>
	<%= render :partial => "form_for_#{@webimage.form_title}", :locals => { :form => form } rescue render :partial => "form", :object => form %>
<% end %>

app/views/super_admin/webimages/index.html.erb
<div class="page-header clearfix">
<div class="title">
	<h1>Imagenes</h1>
</div>
<hr />
<ul class="nav nav-tabs">
	<li class=active> <%= link_to('Listado', super_admin_webimages_path) %></li>
	<li> <%= link_to('Nuevo', new_super_admin_webimage_path) %></li>
</ul>

<div class="module_list">
	<div class="module_partial">
		<%= render :partial => 'list' %>
	</div>
</div>

app/views/super_admin/webimages/new.html.erb
<div class="page-header clearfix">
<div class="title">
	<h1>Nueva Imagen</h1>
</div>
<hr />
<%= render :partial => 'super_admin/template/form_errors', :object => @webimage %>



<%= simple_form_for @webimage, :url => url_for(:controller => 'super_admin/webimages', :action => 'create'), :method => 'post', :html => { :role => "form" } do |form| %>
	<%= render :partial => "form_for_#{@webimage.form_title}", :locals => { :form => form } rescue render :partial => "form", :object => form %>
<% end %>

app/views/super_admin/webimages/show.html.erb
<div class="page-header clearfix">
  <div class="pull-left">
    <h1><%= @webimage.title %></h1>
  </div>
  <div class="pull-right btn-header">
    <%= link_to '<span class="glyphicon glyphicon-pencil"></span> Editar'.html_safe, edit_super_admin_webimage_path(@webimage.id), :class => 'btn btn-primary' %></span>
    &nbsp;
    <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Volver'.html_safe, super_admin_webimages_path, :class => 'btn btn-default' %></span>
  </div>
</div>

<div class=tabs-content>

<p>
  <strong>Id:</strong>
  <%= @webimage.id %>
</p>

  <strong>Nombre:</strong>
  <%= @webimage.title %>
</p>
<p>
  <strong>Modulo:</strong>
  <%= @webimage.module %>
</p>


<%= image_tag(@webimage.image.url(:thumb)) %>





</div>